package com.model;

/**
 * TXianlu generated by MyEclipse Persistence Tools
 */

public class TXianlu implements java.io.Serializable
{

	// Fields

	private Integer id;

	private String xianlumincheng;

	private String fatuandidian;

	private String fatuanshiian;

	private String xianlujiage;

	private String lianxidianhua;

	private String lianxiren;
	
	private String fabushijian;

	private String del;

	public TXianlu()
	{
	}

	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public String getXianlumincheng()
	{
		return this.xianlumincheng;
	}

	public void setXianlumincheng(String xianlumincheng)
	{
		this.xianlumincheng = xianlumincheng;
	}


	public String getFabushijian()
	{
		return fabushijian;
	}

	public void setFabushijian(String fabushijian)
	{
		this.fabushijian = fabushijian;
	}

	public String getFatuandidian()
	{
		return this.fatuandidian;
	}

	public void setFatuandidian(String fatuandidian)
	{
		this.fatuandidian = fatuandidian;
	}

	public String getFatuanshiian()
	{
		return this.fatuanshiian;
	}

	public void setFatuanshiian(String fatuanshiian)
	{
		this.fatuanshiian = fatuanshiian;
	}

	public String getXianlujiage()
	{
		return this.xianlujiage;
	}

	public void setXianlujiage(String xianlujiage)
	{
		this.xianlujiage = xianlujiage;
	}

	public String getLianxidianhua()
	{
		return this.lianxidianhua;
	}

	public void setLianxidianhua(String lianxidianhua)
	{
		this.lianxidianhua = lianxidianhua;
	}

	public String getLianxiren()
	{
		return this.lianxiren;
	}

	public void setLianxiren(String lianxiren)
	{
		this.lianxiren = lianxiren;
	}

	public String getDel()
	{
		return this.del;
	}

	public void setDel(String del)
	{
		this.del = del;
	}

}