package com.model;

/**
 * TYuding generated by MyEclipse Persistence Tools
 */

public class TYuding implements java.io.Serializable
{

	// Fields

	private Integer id;

	private Integer xianluId;

	private Integer userId;
	
	private TUser user;

	// Constructors

	/** default constructor */
	public TYuding()
	{
	}

	/** full constructor */
	public TYuding(Integer xianluId, Integer userId)
	{
		this.xianluId = xianluId;
		this.userId = userId;
	}

	// Property accessors

	public Integer getId()
	{
		return this.id;
	}

	public TUser getUser()
	{
		return user;
	}

	public void setUser(TUser user)
	{
		this.user = user;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	public Integer getXianluId()
	{
		return this.xianluId;
	}

	public void setXianluId(Integer xianluId)
	{
		this.xianluId = xianluId;
	}

	public Integer getUserId()
	{
		return this.userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

}